@startuml
actor Client
participant "API Gateway/Lambda" as Gateway
participant "AddComplianceRuleActivity" as Activity
participant "ComplianceRuleDao" as Dao
database "DynamoDB" as DB

Client -> Gateway: HTTP POST Request (addRule)
Gateway -> Gateway : authenticateRequest

Gateway -> Activity: AddComplianceRuleActivity

Activity -> Activity : validateInputData
alt [if input is invalid]
Activity -> Gateway: throw invalidAttributeValueException
Gateway -> Client : return 400 response

else [valid input]
Activity -> Dao : persist new compliance rule
Dao -> DB : store new rule
DB -> Dao : return 200 response
Dao -> Activity : return new rule
Activity -> Gateway : return addComplianceRule response
Gateway -> Client : return 200 response with rule data

@enduml


Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml